import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../server.js';
let app,base,admin,member;
async function request(route,{method='GET',body,cookie,origin}={}){const r=await fetch(base+'/api/'+route,{method,headers:{...(cookie?{cookie}:{}),...(body?{'Content-Type':'application/json'}:{}),...(origin?{origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
before(async()=>{app=createApp({database:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+app.server.address().port;admin=(await request('login',{method:'POST',body:{email:'admin@clientflow.local',password:'DemoPass123!'}})).cookie;member=(await request('login',{method:'POST',body:{email:'member@clientflow.local',password:'DemoPass123!'}})).cookie});
after(async()=>{await new Promise(r=>app.server.close(r));app.db.close()});
test('workspace requires authentication',async()=>assert.equal((await request('workspace')).status,401));
test('invalid password does not create session',async()=>assert.equal((await request('login',{method:'POST',body:{email:'admin@clientflow.local',password:'wrong'}})).status,401));
test('workspace omits password hashes',async()=>{const r=await request('workspace',{cookie:admin});assert.equal(r.status,200);assert.equal(r.data.projects.length,3);assert.ok(r.data.users.every(u=>!('password' in u)))});
test('member cannot create clients or invoices',async()=>{for(const route of ['clients','invoices'])assert.equal((await request(route,{method:'POST',cookie:member,body:{}})).status,403)});
test('client creation persists and generates an audit entry',async()=>{const r=await request('clients',{method:'POST',cookie:admin,body:{name:'Test Contact',email:'test@example.com',company:'Test Studio'}});assert.equal(r.status,201);const w=(await request('workspace',{cookie:admin})).data;assert.ok(w.clients.some(c=>c.id===r.data.id));assert.ok(w.activity.some(a=>a.action==='Added client Test Studio'))});
test('invalid project foreign keys and dates are rejected',async()=>{const body={name:'Invalid',client_id:999,budget:100,deadline:'2026-11-10'};assert.equal((await request('projects',{method:'POST',cookie:admin,body})).status,404);body.client_id=1;body.deadline='2026-02-30';assert.equal((await request('projects',{method:'POST',cookie:admin,body})).status,400)});
test('task creation and member status changes work',async()=>{const r=await request('tasks',{method:'POST',cookie:member,body:{project_id:1,title:'API integration test',assignee:2}});assert.equal(r.status,201);assert.equal((await request('tasks/'+r.data.id,{method:'PATCH',cookie:member,body:{status:'done'}})).status,200);assert.equal((await request('tasks/'+r.data.id,{method:'PATCH',cookie:member,body:{status:'invalid'}})).status,400)});
test('time entry rejects negative duration and uses authenticated user',async()=>{assert.equal((await request('time',{method:'POST',cookie:member,body:{task_id:1,minutes:-5,note:'Invalid'}})).status,400);const r=await request('time',{method:'POST',cookie:member,body:{task_id:1,minutes:25,note:'Review',user_id:1}});assert.equal(r.status,201);const w=(await request('workspace',{cookie:member})).data;assert.equal(w.time.find(t=>t.id===r.data.id).user_id,2)});
test('invoice state machine prevents skipped or reversed states',async()=>{const r=await request('invoices',{method:'POST',cookie:admin,body:{project_id:1,amount:12000,due:'2026-11-01'}});const route='invoices/'+r.data.id;assert.equal((await request(route,{method:'PATCH',cookie:admin,body:{status:'paid'}})).status,409);for(const status of ['sent','paid'])assert.equal((await request(route,{method:'PATCH',cookie:admin,body:{status}})).status,200);assert.equal((await request(route,{method:'PATCH',cookie:admin,body:{status:'draft'}})).status,409)});
test('cross-origin mutations are blocked',async()=>assert.equal((await request('clients',{method:'POST',cookie:admin,origin:'https://evil.example',body:{}})).status,403));
test('logout revokes session',async()=>{const cookie=(await request('login',{method:'POST',body:{email:'member@clientflow.local',password:'DemoPass123!'}})).cookie;assert.equal((await request('logout',{method:'POST',cookie,body:{}})).status,200);assert.equal((await request('workspace',{cookie})).status,401)});
test('SQL injection text cannot bypass login',async()=>assert.equal((await request('login',{method:'POST',body:{email:"' OR 1=1 --",password:'anything'}})).status,401));
